apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-flux-rolebinding
  namespace: mani-demo
subjects:
- kind: ServiceAccount
  name: deployment
  namespace: mani-demo
roleRef:
  kind: Role
  name: deployment-demo
  apiGroup: rbac.authorization.k8s.io

